import { type Response, type Router } from "express";
import { z } from "zod";
import { Prisma } from "@prisma/client";
import type { PrismaClient } from "@prisma/client";
import { requirePermission } from "../../middleware/permissions.js";
import type { AuditLogService } from "../../services/audit-log.js";
import logger from "../../lib/logger.js";
import { parseRequestBody } from "../_shared/validators.js";
import { sendSuccess, sendCreated, sendNotFound, sendBadRequest, sendError } from "../_shared/responses.js";
import { encodeJsonValue } from "../../types/json-boundaries.js";
import { dispatchOutboundWebhookEvent } from "../../services/outbound-webhooks.js";
import type { AuthenticatedRequest } from "../../types/authenticated-request.js";
import { asyncHandler } from "../../lib/async-handler.js";

const UpsertAutomationRuleSchema = z.object({
  name: z.string().min(2).max(140),
  description: z.string().max(500).optional(),
  enabled: z.boolean().default(true),
  trigger_type: z.enum(["THRESHOLD", "SCHEDULE", "EVENT"]),
  metric: z.string().max(120).optional(),
  operator: z.enum([">", ">=", "<", "<=", "=="]).optional(),
  threshold: z.number().optional(),
  schedule_cron: z.string().max(120).optional(),
  event_type: z.string().max(120).optional(),
  delivery_type: z.enum(["SLACK", "EMAIL", "WEBHOOK"]),
  delivery_target: z.string().min(3).max(2000),
  payload_template: z.record(z.string(), z.unknown()).optional(),
});

const ReportExportFormatSchema = z.object({
  format: z.enum(["csv", "json"]).default("csv"),
});

interface RegisterAutomationRoutesOptions {
  router: Router;
  prisma: PrismaClient;
  auditLogs: AuditLogService;
}

interface AutomationReportPayload {
  generated_at: string;
  window_days: number;
  metrics: Record<string, number>;
}

function decodePayloadTemplate(value: Prisma.JsonValue | null): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return {};
  }
  return value as Record<string, unknown>;
}

function shouldExportScheduledReport(input: {
  triggerType: string;
  eventType: string | null;
  payloadTemplate: Prisma.JsonValue | null;
}): boolean {
  if (input.triggerType !== "SCHEDULE") {
    return false;
  }
  if (input.eventType === "SCHEDULED_REPORT_EXPORT" || input.eventType === "REPORT_EXPORT") {
    return true;
  }
  const template = decodePayloadTemplate(input.payloadTemplate);
  return template.report_export === true;
}

async function createScheduledReportAsset(
  prisma: PrismaClient,
  input: {
    organizationId: string;
    actorUserId: string;
    ruleId: string;
    ruleName: string;
  }
): Promise<{ assetId: string; title: string; payload: AutomationReportPayload }> {
  const windowDays = 30;
  const now = new Date();
  const windowStart = new Date(now);
  windowStart.setDate(windowStart.getDate() - windowDays);

  const [calls, stories, pages, views] = await Promise.all([
    prisma.call.count({
      where: { organizationId: input.organizationId, createdAt: { gte: windowStart } },
    }),
    prisma.story.count({
      where: { organizationId: input.organizationId, generatedAt: { gte: windowStart } },
    }),
    prisma.landingPage.count({
      where: {
        organizationId: input.organizationId,
        status: "PUBLISHED",
        updatedAt: { gte: windowStart },
      },
    }),
    prisma.landingPage.aggregate({
      where: { organizationId: input.organizationId, updatedAt: { gte: windowStart } },
      _sum: { viewCount: true },
    }),
  ]);

  const payload: AutomationReportPayload = {
    generated_at: now.toISOString(),
    window_days: windowDays,
    metrics: {
      calls_processed: calls,
      stories_generated: stories,
      pages_published: pages,
      page_views: views._sum.viewCount ?? 0,
    },
  };

  const title = `Scheduled Report ${now.toISOString().slice(0, 10)}`;
  const asset = await prisma.sharedAsset.create({
    data: {
      organizationId: input.organizationId,
      workspaceId: null,
      ownerUserId: input.actorUserId,
      assetType: "REPORT",
      title,
      description: `Generated by automation rule "${input.ruleName}"`,
      visibility: "ORG",
      metadata: encodeJsonValue({
        report_type: "SCHEDULED_EXPORT",
        rule_id: input.ruleId,
        payload,
      }),
    },
  });

  return { assetId: asset.id, title: asset.title, payload };
}

function reportPayloadToCsv(payload: AutomationReportPayload): string {
  const rows: string[] = [];
  rows.push("metric,value");
  for (const [metric, value] of Object.entries(payload.metrics)) {
    rows.push(`${metric},${value}`);
  }
  return rows.join("\n");
}

export function registerAutomationRoutes({
  router,
  prisma,
  auditLogs,
}: RegisterAutomationRoutesOptions): void {
  // ── Workflow Automation Rules ─────────────────────────────────────

  router.get(
    "/automations",
    requirePermission(prisma, "manage_permissions"),
    asyncHandler(async (req: AuthenticatedRequest, res: Response) => {

      const rules = await prisma.automationRule.findMany({
      where: { organizationId: req.organizationId! },
      orderBy: { updatedAt: "desc" },
      });
      sendSuccess(res, {
      rules: rules.map((r) => ({
        id: r.id,
        name: r.name,
        description: r.description,
        enabled: r.enabled,
        trigger_type: r.triggerType,
        metric: r.metric,
        operator: r.operator,
        threshold: r.threshold,
        schedule_cron: r.scheduleCron,
        event_type: r.eventType,
        delivery_type: r.deliveryType,
        delivery_target: r.deliveryTarget,
        payload_template: r.payloadTemplate,
        last_run_at: r.lastRunAt?.toISOString() ?? null,
        last_run_status: r.lastRunStatus ?? null,
        last_run_error: r.lastRunError ?? null,
        created_at: r.createdAt.toISOString(),
        updated_at: r.updatedAt.toISOString(),
      })),
      });
      
    }
  ));

  router.get(
    "/automations/reports",
    requirePermission(prisma, "manage_permissions"),
    asyncHandler(async (req: AuthenticatedRequest, res: Response) => {

      const reports = await prisma.sharedAsset.findMany({
      where: {
        organizationId: req.organizationId!,
        assetType: "REPORT",
      },
      orderBy: { createdAt: "desc" },
      take: 20,
      });
      sendSuccess(res, {
      reports: reports.map((report) => {
        const metadata = decodePayloadTemplate(report.metadata);
        const payload =
          metadata.payload && typeof metadata.payload === "object"
            ? (metadata.payload as AutomationReportPayload)
            : null;
        return {
          id: report.id,
          title: report.title,
          description: report.description,
          created_at: report.createdAt.toISOString(),
          metrics: payload?.metrics ?? null,
          window_days: payload?.window_days ?? null,
        };
      }),
      });
      
    }
  ));

  router.get(
    "/automations/reports/:assetId/export",
    requirePermission(prisma, "manage_permissions"),
    asyncHandler(async (req: AuthenticatedRequest, res: Response) => {
      const parse = ReportExportFormatSchema.safeParse(req.query);
      if (!parse.success) {
        sendBadRequest(res, "validation_error", parse.error.issues);
        return;
      }

      const asset = await prisma.sharedAsset.findFirst({
      where: {
        id: String(req.params.assetId),
        organizationId: req.organizationId!,
        assetType: "REPORT",
      },
      });
      if (!asset) {
      sendNotFound(res, "report_not_found");
      return;
      }
      const metadata = decodePayloadTemplate(asset.metadata);
      const payload =
      metadata.payload && typeof metadata.payload === "object"
        ? (metadata.payload as AutomationReportPayload)
        : null;
      if (!payload) {
      sendBadRequest(res, "report_payload_missing");
      return;
      }
      if (parse.data.format === "json") {
      res.setHeader("Content-Type", "application/json");
      res.setHeader(
        "Content-Disposition",
        `attachment; filename="${asset.title.replace(/\s+/g, "-").toLowerCase()}.json"`
      );
      res.send(JSON.stringify(payload, null, 2));
      return;
      }

      const csv = reportPayloadToCsv(payload);
      res.setHeader("Content-Type", "text/csv; charset=utf-8");
      res.setHeader(
      "Content-Disposition",
      `attachment; filename="${asset.title.replace(/\s+/g, "-").toLowerCase()}.csv"`
      );
      res.send(csv);
      
    }
  ));

  router.post(
    "/automations",
    requirePermission(prisma, "manage_permissions"),
    asyncHandler(async (req: AuthenticatedRequest, res: Response) => {
      const payload = parseRequestBody(UpsertAutomationRuleSchema, req.body, res);
      if (!payload) {
        return;
      }

      const d = payload;
      const rule = await prisma.automationRule.create({
      data: {
        organizationId: req.organizationId!,
        name: d.name,
        description: d.description,
        enabled: d.enabled,
        triggerType: d.trigger_type,
        metric: d.metric,
        operator: d.operator,
        threshold: d.threshold,
        scheduleCron: d.schedule_cron,
        eventType: d.event_type,
        deliveryType: d.delivery_type,
        deliveryTarget: d.delivery_target,
        payloadTemplate: (d.payload_template ?? undefined) as
          | Prisma.InputJsonValue
          | undefined,
      },
      });
      await auditLogs.record({
      organizationId: req.organizationId!,
      actorUserId: req.userId!,
      category: "AUTOMATION",
      action: "AUTOMATION_RULE_CREATED",
      targetType: "automation_rule",
      targetId: rule.id,
      severity: "INFO",
      ipAddress: req.ip,
      userAgent: req.get("user-agent"),
      });
      sendCreated(res, { id: rule.id });
      
    }
  ));

  router.patch(
    "/automations/:ruleId",
    requirePermission(prisma, "manage_permissions"),
    asyncHandler(async (req: AuthenticatedRequest, res: Response) => {
      const payload = parseRequestBody(UpsertAutomationRuleSchema, req.body, res);
      if (!payload) {
        return;
      }

      const ruleId = String(req.params.ruleId);
      const existing = await prisma.automationRule.findFirst({
      where: { id: ruleId, organizationId: req.organizationId! },
      });
      if (!existing) {
      sendNotFound(res, "automation_rule_not_found");
      return;
      }
      const d = payload;
      await prisma.automationRule.update({
      where: { id: existing.id },
      data: {
        name: d.name,
        description: d.description,
        enabled: d.enabled,
        triggerType: d.trigger_type,
        metric: d.metric,
        operator: d.operator,
        threshold: d.threshold,
        scheduleCron: d.schedule_cron,
        eventType: d.event_type,
        deliveryType: d.delivery_type,
        deliveryTarget: d.delivery_target,
        payloadTemplate: (d.payload_template ?? undefined) as
          | Prisma.InputJsonValue
          | undefined,
      },
      });
      sendSuccess(res, { updated: true });
      
    }
  ));

  router.delete(
    "/automations/:ruleId",
    requirePermission(prisma, "manage_permissions"),
    asyncHandler(async (req: AuthenticatedRequest, res: Response) => {

      const ruleId = String(req.params.ruleId);
      const existing = await prisma.automationRule.findFirst({
      where: { id: ruleId, organizationId: req.organizationId! },
      });
      if (!existing) {
      sendNotFound(res, "automation_rule_not_found");
      return;
      }
      await prisma.automationRule.delete({ where: { id: existing.id } });
      sendSuccess(res, { deleted: true });
      
    }
  ));

  router.post(
    "/automations/:ruleId/run",
    requirePermission(prisma, "manage_permissions"),
    asyncHandler(async (req: AuthenticatedRequest, res: Response) => {
      try {
        const ruleId = String(req.params.ruleId);
        const rule = await prisma.automationRule.findFirst({
          where: { id: ruleId, organizationId: req.organizationId! },
        });
        if (!rule) {
          sendNotFound(res, "automation_rule_not_found");
          return;
        }

        // Simulated delivery execution path for local self-serve testing.
        let status = "SUCCESS";
        let error: string | null = null;
        let reportAsset: { assetId: string; title: string } | null = null;
        try {
          if (
            shouldExportScheduledReport({
              triggerType: rule.triggerType,
              eventType: rule.eventType,
              payloadTemplate: rule.payloadTemplate,
            })
          ) {
            reportAsset = await createScheduledReportAsset(prisma, {
              organizationId: req.organizationId!,
              actorUserId: req.userId!,
              ruleId: rule.id,
              ruleName: rule.name,
            });
          }
          await prisma.notification.create({
            data: {
              organizationId: req.organizationId!,
              userId: req.userId!,
              type: "SYSTEM_ALERT",
              title: `Automation fired: ${rule.name}`,
              body: reportAsset
                ? `Scheduled report generated: ${reportAsset.title}`
                : `Delivery ${rule.deliveryType} -> ${rule.deliveryTarget}`,
              read: false,
              metadata: {
                rule_id: rule.id,
                trigger_type: rule.triggerType,
                report_asset_id: reportAsset?.assetId ?? null,
              } as Prisma.InputJsonValue,
            },
          });
          if (reportAsset) {
            await dispatchOutboundWebhookEvent(prisma, {
              organizationId: req.organizationId!,
              eventType: "scheduled_report_generated",
              payload: {
                report_asset_id: reportAsset.assetId,
                report_title: reportAsset.title,
                rule_id: rule.id,
                rule_name: rule.name,
              },
            }).catch((err) => {
              logger.warn("Outbound webhook dispatch failed", {
                error: err instanceof Error ? err.message : String(err),
                ruleId: rule.id,
              });
            });
          }
        } catch (err) {
          status = "FAILED";
          error = err instanceof Error ? err.message : "Delivery failed";
        }

        await prisma.automationRule.update({
          where: { id: rule.id },
          data: {
            lastRunAt: new Date(),
            lastRunStatus: status,
            lastRunError: error,
          },
        });
        await auditLogs.record({
          organizationId: req.organizationId!,
          actorUserId: req.userId!,
          category: "AUTOMATION",
          action:
            status === "SUCCESS"
              ? "AUTOMATION_RULE_RUN_SUCCESS"
              : "AUTOMATION_RULE_RUN_FAILED",
          targetType: "automation_rule",
          targetId: rule.id,
          severity: status === "SUCCESS" ? "INFO" : "WARN",
          metadata: { status, error },
          ipAddress: req.ip,
          userAgent: req.get("user-agent"),
        });
        sendSuccess(res, {
          status,
          error,
          report_asset_id: reportAsset?.assetId ?? null,
        });
      } catch (err) {
        logger.error("Run automation rule error", { error: err });
        sendError(res, 500, "internal_error", "Failed to run automation rule");
      }
    }
  ));
}
