import { beforeEach, describe, expect, it, vi } from "vitest";
import express from "express";
import { createDashboardRoutes } from "../../src/api/dashboard-routes.js";
import { requestServer } from "../helpers/request-server.js";

function createApp(prisma: any) {
  const app = express();
  app.use(express.json());
  app.use((req, _res, next) => {
    (req as Record<string, unknown>).organizationId = "org-1";
    (req as Record<string, unknown>).userId = "admin-1";
    (req as Record<string, unknown>).userRole = "ADMIN";
    next();
  });
  app.use("/api/dashboard", createDashboardRoutes(prisma));
  return app;
}

describe("dashboard writeback/automation contract", () => {
  const prisma = {
    approvalRequest: {
      findMany: vi.fn(),
    },
    automationRule: {
      findMany: vi.fn(),
    },
    sharedAsset: {
      findMany: vi.fn(),
      findFirst: vi.fn(),
    },
  } as any;

  beforeEach(() => {
    vi.clearAllMocks();
    prisma.approvalRequest.findMany.mockResolvedValue([]);
    prisma.automationRule.findMany.mockResolvedValue([]);
    prisma.sharedAsset.findMany.mockResolvedValue([]);
    prisma.sharedAsset.findFirst.mockResolvedValue(null);
  });

  it("preserves GET /api/dashboard/writebacks mapping", async () => {
    prisma.approvalRequest.findMany.mockResolvedValue([
      {
        id: "wb-1",
        status: "PENDING",
        targetType: "account",
        targetId: "acc-1",
        requestPayload: { action_type: "TASK" },
        requestedByUserId: "user-1",
        reviewerUserId: null,
        reviewNotes: null,
        createdAt: new Date("2026-01-01T00:00:00.000Z"),
        reviewedAt: null,
      },
    ]);

    const app = createApp(prisma);
    const { request, close } = await requestServer(app);
    try {
      const res = await request.get("/api/dashboard/writebacks");

      expect(res.status).toBe(200);
      expect(res.body.writebacks).toEqual([
        {
          id: "wb-1",
          status: "PENDING",
          target_type: "account",
          target_id: "acc-1",
          request_payload: { action_type: "TASK" },
          requested_by_user_id: "user-1",
          reviewer_user_id: null,
          review_notes: null,
          created_at: "2026-01-01T00:00:00.000Z",
          reviewed_at: null,
        },
      ]);
    } finally {
      close();
    }
  });

  it("preserves GET /api/dashboard/automations mapping", async () => {
    prisma.automationRule.findMany.mockResolvedValue([
      {
        id: "auto-1",
        name: "Notify",
        description: "Rule",
        enabled: true,
        triggerType: "EVENT",
        metric: null,
        operator: null,
        threshold: null,
        scheduleCron: null,
        eventType: "CALL_INGESTED",
        deliveryType: "EMAIL",
        deliveryTarget: "ops@example.com",
        payloadTemplate: { include: ["id"] },
        lastRunAt: null,
        lastRunStatus: null,
        lastRunError: null,
        createdAt: new Date("2026-01-01T00:00:00.000Z"),
        updatedAt: new Date("2026-01-02T00:00:00.000Z"),
      },
    ]);

    const app = createApp(prisma);
    const { request, close } = await requestServer(app);
    try {
      const res = await request.get("/api/dashboard/automations");

      expect(res.status).toBe(200);
      expect(res.body.rules).toEqual([
        {
          id: "auto-1",
          name: "Notify",
          description: "Rule",
          enabled: true,
          trigger_type: "EVENT",
          metric: null,
          operator: null,
          threshold: null,
          schedule_cron: null,
          event_type: "CALL_INGESTED",
          delivery_type: "EMAIL",
          delivery_target: "ops@example.com",
          payload_template: { include: ["id"] },
          last_run_at: null,
          last_run_status: null,
          last_run_error: null,
          created_at: "2026-01-01T00:00:00.000Z",
          updated_at: "2026-01-02T00:00:00.000Z",
        },
      ]);
    } finally {
      close();
    }
  });

  it("preserves GET /api/dashboard/automations/reports mapping", async () => {
    prisma.sharedAsset.findMany.mockResolvedValue([
      {
        id: "asset-1",
        title: "Scheduled Report 2026-03-03",
        description: "Generated by automation rule \"Weekly Export\"",
        metadata: {
          payload: {
            generated_at: "2026-03-03T10:00:00.000Z",
            window_days: 30,
            metrics: {
              calls_processed: 10,
              stories_generated: 6,
              pages_published: 3,
              page_views: 150,
            },
          },
        },
        createdAt: new Date("2026-03-03T10:00:00.000Z"),
      },
    ]);

    const app = createApp(prisma);
    const { request, close } = await requestServer(app);
    try {
      const res = await request.get("/api/dashboard/automations/reports");

      expect(res.status).toBe(200);
      expect(res.body.reports).toEqual([
        {
          id: "asset-1",
          title: "Scheduled Report 2026-03-03",
          description: "Generated by automation rule \"Weekly Export\"",
          created_at: "2026-03-03T10:00:00.000Z",
          metrics: {
            calls_processed: 10,
            stories_generated: 6,
            pages_published: 3,
            page_views: 150,
          },
          window_days: 30,
        },
      ]);
    } finally {
      close();
    }
  });

  it("preserves report export contract for csv download", async () => {
    prisma.sharedAsset.findFirst.mockResolvedValue({
      id: "asset-1",
      title: "Scheduled Report 2026-03-03",
      metadata: {
        payload: {
          generated_at: "2026-03-03T10:00:00.000Z",
          window_days: 30,
          metrics: {
            calls_processed: 10,
            stories_generated: 6,
          },
        },
      },
    });

    const app = createApp(prisma);
    const { request, close } = await requestServer(app);
    try {
      const res = await request.get("/api/dashboard/automations/reports/asset-1/export?format=csv");

      expect(res.status).toBe(200);
      expect(res.headers["content-type"]).toContain("text/csv");
      expect(res.text).toContain("metric,value");
      expect(res.text).toContain("calls_processed,10");
      expect(res.text).toContain("stories_generated,6");
    } finally {
      close();
    }
  });
});
